[package]
name = "raqqietka"
version = "0.1.0"
authors = ["Blazej Bucko <blazej.bucko@gmail.com>"]
edition = "2018"

[dependencies]
bytes = "0.4"
tokio = "0.2.0-alpha"
tracing = "0.1"
tracing-subscriber = "0.2.0-alpha"
tracing-futures = { version = "0.1", features = ["tokio-alpha", "std-future"]}


mqtt = { path = "../mqtt" }
core = { path = "../core" }
broker = { path = "../broker" }