[package]
name = "raqqietka"
version = "0.1.0"
authors = ["Blazej Bucko <blazej.bucko@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
simple_logger = "1.0"
bytes = "0.4"
tokio = "0.2.0-alpha"

mqtt = { path = "../mqtt" }
core = { path = "../core" }
broker = { path = "../broker" }