[package]
name = "raqqietka"
version = "0.1.0"
authors = ["Blazej Bucko <blazej.bucko@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
simple_logger = "1.0"
bytes = "0.4"
enum-primitive-derive = "0.1"
num-traits = "^0.1"
regex-cache = "0.2"
tokio = "0.2.0-alpha"
futures-preview = "0.3.0-alpha"
futures-core-preview = "0.3.0-alpha"

mqtt = { path = "../mqtt" }
packets = { path = "../packets" }
broker = { path = "../broker" }

[dev-dependencies]
matches = "0.1"