language: rust

sudo: false
cache:
  cargo: true
#  directories:
#    - kcov/build

rust:
  - nightly

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake

before_script:
  - export PATH=$HOME/.cargo/bin:$PATH
  - cargo install --force cargo-travis
  - cargo install --force clippy
  #- .travisci/install_dependencies.sh

after_success:
#  - cargo clippy
  - cargo coveralls
  - bash <(curl -s https://codecov.io/bash)