version: 2
jobs:
  build:
    docker:
      - image: rust:latest
    steps:
      - checkout
      - run:
          name: Cargo build
          command: cargo build
      - run:
          name: Cargo test
          command: cargo test
#      - run:
#          name: Cargo bench
#          command: cargo bench
