version: 2
jobs:
  build:
    docker:
      - image: rust:latest
    steps:
      - checkout
      - run:
          name: Cargo build
          command: cargo +nightly build
      - run:
          name: Cargo test
          command: cargo +nightly test
      - run:
          name: Cargo bench
          command: cargo +nightly bench
