[package]
name = "mqtt"
version = "0.1.0"
authors = ["Blazej Bucko <blazej.bucko@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
bytes = "0.4"
num-traits = "^0.1"
tokio = "0.2.0-alpha"
futures-preview = "0.3.0-alpha"
broker = {path = "../broker"}
packets = {path = "../packets"}