[package]
name = "core"
version = "0.1.0"
authors = ["Blazej Bucko <blazej.bucko@gmail.com>"]
edition = "2018"

[dependencies]
tracing = "0.1"
bytes = "0.5"

num-traits = "0.2"
enum-primitive-derive = "0.1"