[package]
name = "core"
version = "0.1.0"
authors = ["Blazej Bucko <blazej.bucko@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
bytes = "0.4"

num-traits = "^0.1"
enum-primitive-derive = "0.1"