[package]
name = "core"
version = "0.1.0"
authors = ["Blazej Bucko <blazej.bucko@gmail.com>"]
edition = "2018"

[dependencies]
tracing = { version = "0.1", features = ["std"], default-features = false }
bytes = "1"